apiVersion : apps/v1
kind: Deployment
metadata:
  name: aksimage 
spec:
  replicas: 6000
  selector:
    matchLabels:
      app: aksimage
  template:
    metadata:
      labels: 6000
        app: aksimage 
    spec:
      containers:
        - name: aksimage 
          image: azurecontainerregistry7777.azurecr.io/aksimage
          ports:
          - containerPort: 80
